Add Swedish translation
Umweltzone/Umweltzone pull request #84
Opened 2020-10-10 16:37 UTC by fejd

2020-10-10 16:39 UTC, fejd commented
This commit resolves #76

2020-10-10 22:02 UTC, johnjohndoe commented on Umweltzone/src/main/res/values-sv/ckchangelog.xml
> +  Copyright (C) 2019  Tobias Preuss
Please change to `Copyright (C) 2020  Fredrik Henricsson`.

2020-10-10 22:17 UTC, johnjohndoe requested changes
Hey @fejd, thank you - your translation is technical almost perfect. Please have a look at my few comments. It would be great if you could `git commit --amend` the desired changes to your commit and then `git push --force` it to update this pull request.

2020-10-10 22:17 UTC, johnjohndoe commented on Umweltzone/src/main/res/values-sv/strings.xml
> +  Copyright (C) 2020  Tobias Preuss
Please change to `Copyright (C) 2020  Fredrik Henricsson`.

2020-10-10 22:17 UTC, johnjohndoe commented on Umweltzone/src/main/res/values-sv/ckchangelog.xml
> +</resources>
You are missing the translation for `changelog_error_resource_not_android_5`. See _values/ckchangelog.xml_.

2020-10-10 22:17 UTC, johnjohndoe commented on Umweltzone/src/main/res/values-sv/ckchangelog.xml
> +  Copyright (C) 2019  Tobias Preuss
Please change to `Copyright (C) 2020  Fredrik Henricsson`.

2020-10-11 21:36 UTC, fejd commented
Thanks, I'll fix the comments and push an update soon!

2020-10-12 09:00 UTC, johnjohndoe approved these changes
Tack så mycket @fejd for the Swedish translation. I checked it and it looks great. :+1:

2020-10-12 09:04 UTC, merged

2020-10-13 07:57 UTC, johnjohndoe commented
:arrow_forward: If you have time there is a few strings to translate [here](https://github.com/Umweltzone/roadsigns/issues/9).